# Generated by Django 4.2 on 2023-04-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='display_name',
            field=models.CharField(default='ad', max_length=100),
            preserve_default=False,
        ),
    ]
